const defaultCounty= {"county":{
    "id": 4,
    "name": "Marion",
    "description": "Description:",
    "url": "https://www.pa.marion.fl.us/PropertySearch.aspx",
    "propertySearchUrl": "https://www.pa.marion.fl.us/PropertySearch.aspx",
    "yearBuilt": "Year Built",
    "qualityGrade": "Quality Grd",
    "squareFootage": "Total SFLA",
    "land": null,
    "landValue": "Total Land Value",
    "buildingValue": "Total Building Value",
    "totalBuildingArea": "Total Building Area",
    "foundation": "Foundation:",
    "use": "Property Use:",
    "heatSource": "Heat Source",
    "heatMethod": "Heat Method",
    "stories": "Stories",
    "baths": "2 Fixture Baths,3 Fixture Baths,4 Fixture Baths,5 Fixture Baths,6 Fixture Baths,7 Fixture Baths",
    "bedrooms": "# Bedrooms:",
    "parcelId": "Parcel ID:",
    "address": null,
    "owner": "Owner(s)",
    "mailingAddress": "Mailing Address",
    "patios": "Patio",
    "porches": "Porch",
    "garage": null,
    "floorType": "Floor Type",
    "roofType": "Roof Type",
    "roofShape": null,
    "roofCover": "Roof Cover",
    "wallHeight": null,
    "extWall": "Exterior Wall",
    "intWall": "Wall Type",
    "pool": null,
    "purchasePrice": null,
    "purchaseDate": null,
    "state": 1
  },
  "attributes": [{attribute:'yearBuilt',integer:true,single:true},{attribute:'foundation',integer:false,single:true},
  {attribute:'parcelId',integer:false,single:false},
  {attribute:'owner',integer:false,single:false},
  {attribute:'mailingAddress',integer:false,single:false},
  {attribute:'description',integer:false,single:false},{attribute:'heatSource',integer:false,single:true},{attribute:'heatMethod',integer:false,single:true},
  {attribute:'roofCover',integer:false,single:true},
  {attribute:'roofType',integer:false,single:true},
  {attribute:'extWall',integer:false,single:true},
  {attribute:'floorType',integer:false,single:true},
  {attribute:'intWall',integer:false,single:true},{attribute:'squareFootage',integer:true,single:true},
  {attribute:'totalBuildingArea',integer:true,single:true},{attribute:'qualityGrade',integer:false,single:true},
  {attribute:'description',integer:false,single:true},{attribute:'stories',integer:true,single:true},
  {attribute:'baths',integer:true,single:true},
  {attribute:'bedrooms',integer:true,single:true},
  {attribute:'use',integer:false,single:false},
  {attribute:'land',integer:false,single:true},{attribute:'buildingValue',integer:true,single:true},
  {attribute:'otherStruct',integer:false,single:true},{attribute:'porches',integer:false,single:false},
  {attribute:'patios',integer:false,single:false},{attribute:'garage',integer:false,single:false},
  {attribute:'pool',integer:false,single:true},{attribute:'alarms',integer:false,single:true},
  {attribute:'security',integer:false,single:true},
  {attribute:'landValue',integer:true,single:true}
  ]
}

exports.defaultCounty = defaultCounty;