version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "UaigQuoter"
s3_bucket = "browsersprieto29"
s3_prefix = "UaigQuoter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
