AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  CountyScraper
  County Scraping Function
Resources:
  ChromePuppeteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Serverless Chrome/Puppeteer Layer
      ContentUri: layers/puppeteer/
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x

  CountyScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Scraping County Data
      CodeUri: scraperFunction/
      Handler: app.lambdaHandler
      Timeout: 60
      MemorySize: 2048 # Chrome will require higher memory
      Runtime: nodejs14.x
      Layers:
        - !Ref ChromePuppeteerLayer # Attach Our Chrome Layer